# Generated by Django 4.1.1 on 2022-10-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioOfrecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicioOfrecidoNombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('servicioOfrecidoDesripcion', models.CharField(max_length=125, verbose_name='Descripción')),
                ('servicioOfrecidoActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
