# Generated by Django 4.1.1 on 2022-10-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoGestionNombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('estadoGestionDescripcion', models.CharField(max_length=125, verbose_name='Descripción')),
                ('estadoGestionActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
