# Generated by Django 4.1.1 on 2022-10-23 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_estadogestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaDescripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('categoriaActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoriaDescripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('subCategoriaActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('categoria_idCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
