# Generated by Django 4.1.1 on 2022-10-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioNombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('usuarioApellido', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('usuarioTipoDocumento', models.CharField(choices=[('CC', 'Cédula de cuidadanía'), ('CE', 'Cédula extranjera'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil')], default='CC', max_length=4, verbose_name='Tipo de documento')),
                ('usuarioNumeroDocumento', models.CharField(max_length=50, verbose_name='Numero de documento')),
                ('usuarioCorreo', models.CharField(max_length=55, verbose_name='Correo electrónico')),
                ('usarioRol', models.CharField(choices=[('Comercial', 'Comercial'), ('Mercadeo', 'Mercadeo'), ('Administrador', 'Administrador'), ('Soporte', 'Soporte')], default='Mercadeo', max_length=15, verbose_name='Rol de usuario')),
                ('usuarioActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitorEstadoPeriodo', models.CharField(choices=[('SEMANA', 'Semana'), ('MES', 'Mes')], default='SEMANA', max_length=10, verbose_name='Periodo de tiempo')),
                ('monitorEstadoMeta', models.CharField(max_length=3, verbose_name='Meta de gestion')),
                ('monitorEstadoValor', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Valor porcentual de gestion')),
                ('monitorEstadoDescripcion', models.CharField(max_length=45, verbose_name='Descripcion de monitor de estado')),
                ('monitorEstadoActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('monitorEstadoIdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoriaNombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('auditoriaDescripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('auditoriaRegistro', models.DateField(verbose_name='Fecha de registro')),
                ('auditoriaIdGestionCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.gestioncliente', verbose_name='Gestion cliente')),
                ('auditoriaIdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
