# Generated by Django 4.1.1 on 2022-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestionClienteRegistro', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de registro')),
                ('gestionClienteObservacion', models.CharField(max_length=254, verbose_name='Descripción de gestion')),
                ('gestionClienteTiempoInvertido', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='tiempo de horas y fracción')),
            ],
        ),
    ]
